//GENERAL USE
export const NOT_LOADING = 'NOT_LOADING';
export const NO_BUTTON = 'NO_BUTTON';

//COMPETITION
export const ADD_COMPETITION_BUTTON = 'ADD_COMPETITION_BUTTON';
export const DELETE_COMPETITION_BUTTON = 'DELETE_COMPETITION_BUTTON';
export const UPDATE_PARTICIPANT_LEDGER_BUTTON =
  'UPDATE_PARTICIPANT_LEDGER_BUTTON';
export const UPDATE_PARTICIPANT_TARGET_BUTTON =
  'UPDATE_PARTICIPANT_TARGET_BUTTON';
export const UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON =
  'UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON';
export const UPDATE_COMPETITION_BUTTON = 'UPDATE_COMPETITION_BUTTON';
export const REMOVE_ADMIN_FROM_COMPETITION_BUTTON =
  'REMOVE_ADMIN_FROM_COMPETITION_BUTTON';
export const REQUEST_TO_JOIN_COMPETITION_BUTTON =
  'REQUEST_TO_JOIN_COMPETITION_BUTTON';

//FRIEND
export const DELETE_FRIEND_BUTTON = 'DELETE_FRIEND_BUTTON';

//GOAL
export const UPDATE_GOAL_BUTTON = 'UPDATE_GOAL_BUTTON';
export const UPDATE_GOAL_LEDGER_BUTTON = 'UPDATE_GOAL_LEDGER_BUTTON';
export const ADD_GOAL_BUTTON = 'ADD_GOAL_BUTTON';
export const DELETE_GOAL_BUTTON = 'DELETE_GOAL_BUTTON';

//REQUEST
export const ADD_REQUEST_BUTTON = 'ADD_REQUEST_BUTTON';
export const DELETE_REQUEST_BUTTON = 'DELETE_REQUEST_BUTTON';
export const ACCEPT_REQUEST_BUTTON = 'ACCEPT_REQUEST_BUTTON';
export const REJECT_REQUEST_BUTTON = 'REJECT_REQUEST_BUTTON';

//USER
export const LOGIN_OR_REGISTER_BUTTON = 'LOGIN_OR_REGISTER_BUTTON';
export const UPDATE_USER_BUTTON = 'UPDATE_USER_BUTTON';
export const CHANGE_PASSWORD_BUTTON = 'CHANGE_PASSWORD_BUTTON';
export const DELETE_USER_BUTTON = 'DELETE_USER_BUTTON';

export type CompetitionButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof ADD_COMPETITION_BUTTON
  | typeof UPDATE_PARTICIPANT_LEDGER_BUTTON
  | typeof UPDATE_PARTICIPANT_TARGET_BUTTON
  | typeof UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON
  | typeof DELETE_COMPETITION_BUTTON
  | typeof REMOVE_ADMIN_FROM_COMPETITION_BUTTON
  | typeof REQUEST_TO_JOIN_COMPETITION_BUTTON;

export type FriendButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof DELETE_FRIEND_BUTTON;

export type GoalButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof ADD_GOAL_BUTTON
  | typeof UPDATE_GOAL_BUTTON
  | typeof UPDATE_GOAL_LEDGER_BUTTON
  | typeof DELETE_GOAL_BUTTON;

export type RequestButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof ADD_REQUEST_BUTTON
  | typeof DELETE_REQUEST_BUTTON
  | typeof REJECT_REQUEST_BUTTON
  | typeof ACCEPT_REQUEST_BUTTON;

export type UserButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof LOGIN_OR_REGISTER_BUTTON
  | typeof UPDATE_USER_BUTTON
  | typeof CHANGE_PASSWORD_BUTTON
  | typeof DELETE_USER_BUTTON;
