//GENERAL USE
export const NOT_LOADING = 'NOT_LOADING';
export const NO_BUTTON = 'NO_BUTTON';

//COMPETITION
//general
export const ADD_COMPETITION_BUTTON = 'ADD_COMPETITION_BUTTON';
export const UPDATE_COMPETITION_BUTTON = 'UPDATE_COMPETITION_BUTTON';
export const DELETE_COMPETITION_BUTTON = 'DELETE_COMPETITION_BUTTON';
//participant
export const ACCEPT_INVITE_BUTTON = 'ACCEPT_INVITE_BUTTON';
export const ADMIN_ACCEPT_PARTICIPANT_REQUEST_BUTTON =
  'ADMIN_ACCEPT_PARTICIPANT_REQUEST_BUTTON';
export const UPDATE_PARTICIPANT_LEDGER_BUTTON =
  'UPDATE_PARTICIPANT_LEDGER_BUTTON';
export const UPDATE_PARTICIPANT_TARGET_BUTTON =
  'UPDATE_PARTICIPANT_TARGET_BUTTON';
export const UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON =
  'UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON';
export const REMOVE_SELF_FROM_COMPETITION_BUTTON =
  'REMOVE_SELF_FROM_COMPETITION_BUTTON';
export const ADMIN_KICK_USER_FROM_COMPETITION_BUTTON =
  'ADMIN_KICK_USER_FROM_COMPETITION_BUTTON';
//participant request
export const ADD_PARTICIPANT_REQUEST_BUTTON = 'ADD_PARTICIPANT_REQUEST_BUTTON';
export const DELETE_PARTICIPANT_REQUEST_BUTTON =
  'DELETE_PARTICIPANT_REQUEST_BUTTON';
export const ADMIN_REJECT_PARTICIPANT_REQUEST_BUTTON =
  'ADMIN_REJECT_PARTICIPANT_REQUEST_BUTTON';
//invite
export const ADMIN_ADD_INVITE_BUTTON = 'ADMIN_ADD_INVITE_BUTTON';
export const ADMIN_DELETE_INVITE_BUTTON = 'ADMIN_DELETE_INVITE_BUTTON';
export const REJECT_INVITE_BUTTON = 'REJECT_INVITE_BUTTON';
//admin
export const ACCEPT_ADMIN_REQUEST_BUTTON = 'ACCEPT_ADMIN_REQUEST_BUTTON';
export const RELINQUISH_ADMIN_BUTTON = 'RELINQUISH_ADMIN_BUTTON';
//admin request
export const ADMIN_ADD_ADMIN_REQUEST_BUTTON = 'ADMIN_ADD_ADMIN_REQUEST_BUTTON';
export const REJECT_ADMIN_REQUEST_BUTTON = 'REJECT_ADMIN_REQUEST_BUTTON';

export type CompetitionButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  //general
  | typeof ADD_COMPETITION_BUTTON
  | typeof UPDATE_COMPETITION_BUTTON
  | typeof DELETE_COMPETITION_BUTTON
  //participant
  | typeof UPDATE_PARTICIPANT_LEDGER_BUTTON
  | typeof UPDATE_PARTICIPANT_TARGET_BUTTON
  | typeof UPDATE_PARTICIPANT_INITIAL_VALUE_BUTTON
  | typeof ACCEPT_INVITE_BUTTON
  | typeof ADMIN_ACCEPT_PARTICIPANT_REQUEST_BUTTON
  | typeof REMOVE_SELF_FROM_COMPETITION_BUTTON
  | typeof ADMIN_KICK_USER_FROM_COMPETITION_BUTTON
  //participant request
  | typeof ADD_PARTICIPANT_REQUEST_BUTTON
  | typeof DELETE_PARTICIPANT_REQUEST_BUTTON
  | typeof ADMIN_ADD_INVITE_BUTTON
  //invite
  | typeof ADMIN_REJECT_PARTICIPANT_REQUEST_BUTTON
  | typeof ADMIN_DELETE_INVITE_BUTTON
  | typeof REJECT_INVITE_BUTTON
  //admin
  | typeof ACCEPT_ADMIN_REQUEST_BUTTON
  | typeof RELINQUISH_ADMIN_BUTTON
  //admin request
  | typeof ADMIN_ADD_ADMIN_REQUEST_BUTTON
  | typeof REJECT_ADMIN_REQUEST_BUTTON;

//FRIEND
export const DELETE_FRIEND_BUTTON = 'DELETE_FRIEND_BUTTON';

export type FriendButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof DELETE_FRIEND_BUTTON;

//GOAL
export const UPDATE_GOAL_BUTTON = 'UPDATE_GOAL_BUTTON';
export const UPDATE_GOAL_LEDGER_BUTTON = 'UPDATE_GOAL_LEDGER_BUTTON';
export const ADD_GOAL_BUTTON = 'ADD_GOAL_BUTTON';
export const DELETE_GOAL_BUTTON = 'DELETE_GOAL_BUTTON';

export type GoalButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof ADD_GOAL_BUTTON
  | typeof UPDATE_GOAL_BUTTON
  | typeof UPDATE_GOAL_LEDGER_BUTTON
  | typeof DELETE_GOAL_BUTTON;

//REQUEST
export const ADD_FRIEND_REQUEST_BUTTON = 'ADD_FRIEND_REQUEST_BUTTON';
export const DELETE_FRIEND_REQUEST_BUTTON = 'DELETE_FRIEND_REQUEST_BUTTON';
export const ACCEPT_FRIEND_REQUEST_BUTTON = 'ACCEPT_FRIEND_REQUEST_BUTTON';
export const REJECT_FRIEND_REQUEST_BUTTON = 'REJECT_FRIEND_REQUEST_BUTTON';

export type FriendRequestButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof ADD_FRIEND_REQUEST_BUTTON
  | typeof DELETE_FRIEND_REQUEST_BUTTON
  | typeof REJECT_FRIEND_REQUEST_BUTTON
  | typeof ACCEPT_FRIEND_REQUEST_BUTTON;

//USER
export const LOGIN_OR_REGISTER_BUTTON = 'LOGIN_OR_REGISTER_BUTTON';
export const UPDATE_USER_BUTTON = 'UPDATE_USER_BUTTON';
export const CHANGE_PASSWORD_BUTTON = 'CHANGE_PASSWORD_BUTTON';
export const DELETE_USER_BUTTON = 'DELETE_USER_BUTTON';

export type UserButtonTypes =
  | typeof NOT_LOADING
  | typeof NO_BUTTON
  | typeof LOGIN_OR_REGISTER_BUTTON
  | typeof UPDATE_USER_BUTTON
  | typeof CHANGE_PASSWORD_BUTTON
  | typeof DELETE_USER_BUTTON;
