using System.Collections.Generic;

namespace Core.Errors
{
  public class ApiValidationError
  {
    public int StatusCode { get; set; }
    public string Message { get; }
    //list of validation errors, generated by default ApiController, see override in startup
    public IEnumerable<string> Errors { get; set; }

    //will always be 400 error
    public ApiValidationError(IEnumerable<string> errors)
    {
      StatusCode = 400;
      Message = "Something was wrong with your request.";
      Errors = errors;
    }
  }
}