using System.Collections.Generic;

namespace API.Errors
{
  public class ApiValidationError : ApiError
  {
    public ApiValidationError() : base(400) //will always be 400 error
    {
    }

    //list of validation errors, generated by default ApiController, see override in startup
    public IEnumerable<string> Errors { get; set; }
  }
}