using System;

namespace Core.Entities
{
  public class Comment : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }
    public string Body { get; set; }
    public DateTime CreatedAt { get; set; }
    public virtual User Author { get; set; }
    public virtual Goal Competition { get; set; }
  }
}