using System;

namespace Core.Entities
{
  public class CompetitionComment : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }
    public Guid CompId { get; set; }
    public string Body { get; set; }
    public Guid AuthorId { get; set; }
    public DateTime CreatedAt { get; set; }

    //relationships
    public virtual CompetitionGoal Comp { get; set; }
    public virtual User Author { get; set; }
  }
}