using System;
using System.Collections.Generic;

namespace Core.Entities
{
  public class CompetitionGoal : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    public string Name { get; set; }

    //Time in days
    public int Duration { get; set; }

    //Day goal starts (not created)
    public DateTime StartDate { get; set; }

    public GoalType Type { get; set; }

    //Optional
    public string Description { get; set; }

    //Cumulative and difference types only 
    public string Units { get; set; } = null;

    //pass fail goals only - number of days per week
    public int Frequency { get; set; }

    public bool isHighestScoreWins { get; set; } = true;

    //Determines who can see goal - only user (true) or user friends (false)
    public bool IsPrivate { get; set; }

    //relationships
    public virtual ICollection<CompetitionParticipant> Participants { get; set; }
    public virtual ICollection<CompetitionLetter> Letters { get; set; }
    public virtual ICollection<CompetitionAdmin> Admins { get; set; }
    public virtual ICollection<CompetitionComment> Comments { get; set; }
  }
}