using System;

namespace Core.Entities
{
  public class CompetitionLetter : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    //Competition Id
    public Guid CompId { get; set; }

    //User Id of subject
    public Guid ReceiverId { get; set; }

    public LetterType Type { get; set; }

    //public DateTime ExpirationDate { get; set; }
    //TODO how to make expire?

    //relationships
    public virtual CompetitionGoal Comp { get; set; }
    public virtual User Receiver { get; set; }
  }

  //UserInvited - Tell user they were invited to join competition
  //UserRequested - Tell admins a user asked to join competition
  //UserAdded - Tell user their request to join competition was accepted
  //UserKicked - Tell user they were kicked from a competition
  //CompDeleted - Tell user a competition was deleted
  //AdminRequested - Tell user they were asked to be a competition admin
  public enum LetterType
  {
    UserInvited,
    UserRequested,
    UserAdded,
    UserKicked,
    CompDeleted,
    AdminRequested,
  }
}