using System;

namespace Core.Entities
{
  public enum GoalType { passfail, total, difference }

  public class Goal : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    public string Name { get; set; }

    //User Key
    public Guid UserId { get; set; }

    public User User { get; set; }

    //Time in days
    public int Duration { get; set; }

    //Day goal starts (not created)
    public DateTime StartDate { get; set; }

    public string Type { get; set; }

    //Optional
    public string Description { get; set; }

    //Total and difference types only 
    public string Units { get; set; }

    //passfail - number of times per week (7 is daily, min is 1)
    //total or difference - number of units a user wishes to achieve/gain
    //For competition goals, -1 means lowest score wins, anything else means highest score wins
    public int Total { get; set; }

    //Determines who can see goal - only user (true) or user friends (false)
    public bool IsPrivate { get; set; }

    //Competition Key
    public Nullable<Guid> CompId { get; set; } = null;

    //Comma seperated array - saved as JSON 
    public string Tracker { get; set; }
  }
}