using System;

namespace Core.Entities
{
  public class Letter : BaseEntity
  {
    //Key, Autogenerated
    // public Guid Id { get; set; }

    //Competition Key
    public Guid CompId { get; set; }

    //Standard format, created by backend
    public string Message { get; set; }

    //User Key of receiver
    public Guid ReceiverId { get; set; }

    //User Key of sender
    public Guid SenderId { get; set; }

    public LetterType Type { get; set; }

    //public DateTime ExpirationDate { get; set; }
    //TODO how to make expire?
  }

  //ToUser - Tell User an Admin invited user to join competition
  //From User - Tell Admin a User asked to join competition
  //UserAdded - Tell User their request to join competition was accepted
  //UserKicked - Tell User they were kicked from a competition
  //CompDeleted - Tell User a competition was deleted
  //RequestAdmin - Tell User an Admin asked them to be a competition Admin

  public enum LetterType
  {
    ToUser,
    FromUser,
    UserAdded,
    UserKicked,
    CompDeleted
  }
}