using System;

namespace Core.Entities
{
  public class UserNotification : BaseEntity
  {
    public UserNotification()
    {

    }

    //autogenerated
    public Guid Id { get; set; }

    //User Id of subject
    public Guid UserId { get; set; }

    //message displayed to user
    public string Message { get; set; }

    //relationships
    public virtual User User { get; set; }
  }
}