using System;

namespace Core.Entities
{
  public enum GoalType { passfail, cumulative, difference }

  public class UserGoal : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    public string Name { get; set; }

    //User Key
    public Guid UserId { get; set; }

    //Time in days
    public int Duration { get; set; }

    //Day goal starts (not created)
    public DateTime StartDate { get; set; }

    public GoalType Type { get; set; }

    //Optional
    public string Description { get; set; }

    //cumulative and difference types only 
    public string Units { get; set; }

    //passfail - number of times per week (7 is daily, min is 1)
    //cumulative or difference - number of units a user wishes to achieve
    public decimal? Target { get; set; }

    //Determines who can see goal - only user (true) or user friends (false)
    public bool IsPrivate { get; set; }

    //Comma seperated array - saved as JSON 
    public string Ledger { get; set; }

    public decimal? InitialValue { get; set; }

    //relationships
    public User User { get; set; }
  }
}