using System;
using System.Collections.Generic;

namespace Core.Entities
{
  public class User : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    public string Name { get; set; }

    //must be unique
    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime RegisterDate { get; set; } = DateTime.Now;

    //decides if other users can search for this user
    public bool IsSearchable { get; set; }

    //relationships
    public virtual ICollection<UserFriendship> User1Friends { get; set; }
    public virtual ICollection<UserFriendship> User2Friends { get; set; }
    public virtual ICollection<UserFriendRequest> Requesters { get; set; }
    public virtual ICollection<UserFriendRequest> Requestees { get; set; }
  }
}