using System;
using System.Collections.Generic;

namespace Core.Entities
{
  public class User : BaseEntity
  {
    //Key, Autogenerated
    public Guid Id { get; set; }

    public string Name { get; set; }

    //must be unique
    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime RegisterDate { get; set; } = DateTime.Now;

    //decides if other users can search for this user
    public bool IsSearchable { get; set; }

    //relationships
    public virtual ICollection<UserGoal> UserGoals { get; set; }
    public virtual ICollection<UserFriendship> User1Friends { get; set; }
    public virtual ICollection<UserFriendship> User2Friends { get; set; }
    public virtual ICollection<UserFriendRequest> Senders { get; set; }
    public virtual ICollection<UserFriendRequest> Receivers { get; set; }
    public virtual ICollection<CompetitionParticipant> Participations { get; set; }
    public virtual ICollection<CompetitionComment> Comments { get; set; }
    public virtual ICollection<CompetitionAdmin> AdminJobs { get; set; }
    public virtual ICollection<CompetitionParticipantRequest> ParticipantRequests { get; set; }
    public virtual ICollection<CompetitionAdminRequest> AdminRequests { get; set; }
    public virtual ICollection<CompetitionInvite> Invites { get; set; }
    public virtual ICollection<UserNotification> Notifications { get; set; }
  }
}