import { GoalTypeEnum } from '../shared/models/goal';

const d = new Date();
const dayThree = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000);
const dayTen = new Date(d.getTime() - 10 * 24 * 60 * 60 * 1000);
const dayPlusThree = new Date(d.getTime() + 3 * 24 * 60 * 60 * 1000);

export const dummyGoals = [
  {
    id: '001',
    name: 'Goal 1',
    userId: '101',
    duration: 7,
    startDate: dayThree,
    type: GoalTypeEnum.passfail,
    description: 'pass/fail goal',
    units: '',
    total: 7,
    isPrivate: true,
    compId: '201',
    tracker: [true, false, true, null, null, null, null],
  },
  {
    id: '002',
    name: 'Goal 2',
    userId: '101',
    duration: 7,
    startDate: dayThree,
    type: GoalTypeEnum.total,
    description: 'total goal',
    units: 'miles',
    total: 7,
    isPrivate: true,
    compId: null,
    tracker: [1, 2, 3],
  },
  {
    id: '003',
    name: 'Goal 3',
    userId: '101',
    duration: 7,
    startDate: dayThree,
    type: GoalTypeEnum.difference,
    description: 'difference goal',
    units: 'lbs',
    total: 155,
    isPrivate: true,
    compId: null,
    tracker: [145, null, null, null],
  },
  {
    id: '004',
    name: 'Goal 4',
    userId: '101',
    duration: 7,
    startDate: dayTen,
    type: GoalTypeEnum.passfail,
    description: 'past pass/fail goal',
    units: '',
    total: 7,
    isPrivate: true,
    compId: '204',
    tracker: [true, false, true, false, true, false, true],
  },
  {
    id: '005',
    name: 'Goal 5',
    userId: '101',
    duration: 7,
    startDate: dayTen,
    type: GoalTypeEnum.total,
    description: 'past total goal',
    units: 'miles',
    total: 7,
    isPrivate: true,
    compId: null,
    tracker: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    id: '006',
    name: 'Goal 6',
    userId: '101',
    duration: 7,
    startDate: dayTen,
    type: GoalTypeEnum.difference,
    description: 'past difference goal',
    units: 'lbs',
    total: 7,
    isPrivate: true,
    compId: null,
    tracker: [145, null, null, null, 154, null, null, 160],
  },
  {
    id: '007',
    name: 'Goal 7',
    userId: '101',
    duration: 7,
    startDate: dayPlusThree,
    type: GoalTypeEnum.passfail,
    description: 'future pass/fail goal',
    units: '',
    total: 7,
    isPrivate: true,
    compId: '207',
    tracker: [],
  },
  {
    id: '008',
    name: 'Goal 8',
    userId: '101',
    duration: 7,
    startDate: dayPlusThree,
    type: GoalTypeEnum.total,
    description: 'future total goal',
    units: 'miles',
    total: 7,
    isPrivate: true,
    compId: null,
    tracker: [],
  },
  {
    id: '009',
    name: 'Goal 9',
    userId: '101',
    duration: 7,
    startDate: dayPlusThree,
    type: GoalTypeEnum.difference,
    description: 'future difference goal',
    units: 'lbs',
    total: 7,
    isPrivate: true,
    compId: null,
    tracker: [],
  },
];
